// apps/baltown/src/main.tsx
/* @refresh reload */
import { render } from 'solid-js/web'
import { Router, Route } from '@solidjs/router'
import { Bassline } from '@bassline/core'
import { createRemoteRoutes } from '@bassline/remote-browser'
import { BasslineProvider, WebSocketProvider } from '@bassline/solid'
import Layout from './Layout'
import Home from './pages/Home'
import Browse from './pages/Browse'
import Compose from './pages/Compose'
import ValView from './pages/ValView'
import VersionHistory from './pages/VersionHistory'
import Cells from './pages/Cells'
import TemplateGallery from './pages/templates/TemplateGallery'

// Configuration
const WS_PORT = 9112
const WS_URL = `ws://localhost:${WS_PORT}`

// Create Bassline instance with remote routes
const bl = new Bassline()
bl.install(createRemoteRoutes())

// Connect to daemon
bl.put('bl:///remote/ws/daemon', {}, {
  uri: WS_URL,
  mount: '/r'  // Access remote resources via bl:///r/*
})

// Render app
render(() => (
  <WebSocketProvider url={WS_URL}>
    <BasslineProvider value={bl}>
      <Router root={Layout}>
        <Route path="/" component={Home} />
        <Route path="/browse" component={Browse} />
        <Route path="/compose" component={Compose} />
        <Route path="/compose/:type" component={Compose} />
        <Route path="/v/:owner/:name" component={ValView} />
        <Route path="/v/:owner/:name/edit" component={Compose} />
        <Route path="/v/:owner/:name/versions" component={VersionHistory} />
        <Route path="/cells" component={Cells} />
        <Route path="/templates" component={TemplateGallery} />
      </Router>
    </BasslineProvider>
  </WebSocketProvider>
), document.getElementById('root')!)

// apps/editor/src/main.jsx
import { createRoot } from 'react-dom/client'
import { Bassline } from '@bassline/core'
import { createRemoteRoutes } from '@bassline/remote-browser'
import { BasslineProvider, WebSocketProvider } from '@bassline/react'
import App from './App.jsx'
import './styles/main.css'

// Configuration - can be overridden via environment
const WS_PORT = import.meta.env.VITE_BL_WS_PORT || 9112

// Create browser-side Bassline with remote connection
const bl = new Bassline()
bl.install(createRemoteRoutes())

// Connect to daemon via WebSocket
// Access remote resources via bl:///r/* (e.g., bl:///r/cells → remote bl:///cells)
bl.put('bl:///remote/ws/daemon', {}, {
  uri: `ws://localhost:${WS_PORT}`,
  mount: '/r'
})

createRoot(document.getElementById('root')).render(
  <WebSocketProvider url={`ws://localhost:${WS_PORT}`}>
    <BasslineProvider value={bl}>
      <App />
    </BasslineProvider>
  </WebSocketProvider>
)
